---
title: "Investment Resources List"
description: |
  This is a list of public resources to share. Always check data quality, specially for free stuff.
site: distill::distill_website
---

# Macro Resources

-   **Our World in Data**: Good for visualizing long term data like population trends, growth, debt, poverty, taxation, etc... Go to [ourworldindata.org](https://ourworldindata.org) and check for example [population growth data](https://ourworldindata.org/population-growth), [debt over gdp by country](https://ourworldindata.org/grapher/gross-public-sector-debt-as-a-proportion-of-gdp) or [trade and globalization data](https://ourworldindata.org/trade-and-globalization) for the whole world.

-   **IMF Data Portal**: [data.imf.org](https://www.imf.org/en/Data). You can access World Economic Outlook Database ([here](https://www.imf.org/en/Publications/WEO/weo-database/2025/april) is the April 2025 version), where you can do analysis of countries, groups or download the whole database.

-   **FRED**: the St. Louis Fred site has a lot of historical data, mainly from the US and also mainly about prices like interest rates, inflation, etc... Visit <https://fred.stlouisfed.org>

-   **Index Of Economic Freedom**: this classifies countries by rule of law, market openness, etc... Countries with greater freedom do better in the long run. You can visualize the evolution and compare between countries and their freedom components [here](https://www.heritage.org/index/pages/dataviz)

# Educational Resources

These are very valuable IMHO

-   **GummyStuff**. This is an old resource from a great guy, professor Peter Ponzo. He was a math professor and started teaching himself finance with these tutorials, and stopped posting in 2010 and died in 2020. But he was a great teacher. This motivated me to learn more about finance. The original site is archived [here](https://www.gummystuff.org), and there is an easier to use version in [this site](https://www.financialwisdomforum.org/gummy-stuff-tutorials/).

-   **Bionic Turtle** has great video tutorials. The old stuff is the best, for example the [options pricing playlist](https://www.youtube.com/watch?v=FBVo8l1WgTg&list=PL4108D90CA93915EB), the [Gordon Discount Model](https://www.youtube.com/watch?v=cN-sVL7OWcY), and many more. Visit [https://www.youtube.com/\@bionicturtle](https://www.youtube.com/@bionicturtle){.uri}

# Valuation Resources

-   **Research Affiliates**. They have the Asset Allocation Interactive Tool [here](https://interactive.researchaffiliates.com/asset-allocation), where you can see current valuations and historical references. Go to <https://www.researchaffiliates.com> and subscribe, it's free.

-   **CAPE Valuations:** country valuations using the CAPE ratio, produced by Barclays. It is hidden, but [go to this link](https://indices.cib.barclays/IM/21/en/indices/static/historic-cape.app) to see this data.

-   **Gurufocus** (freemium): good data for specific companies, some data is paid. Go to <https://www.gurufocus.com>

# Backtesting and prices

-   **Portfolio Visualizer.** has the best data quality, and great asset allocation tools (very powerful). Free data goes just up to 2008. Paid goes up to 1970, and you can upload your own. It does inflation adjusted data, etc... Go to <https://www.portfoliovisualizer.com>, or the legacy interface at <https://legacy.portfoliovisualizer.com> which I prefer.

-   **OpenBB**. Tries to be a Bloomberg clone and looks very promising. Visit <https://openbb.co>

# Knowing the market size

-   **FinViz**. Good for understanding the size of the equity market. Go to the 'Maps' Menu [in this link](https://finviz.com/map.ashx), where you can see the size of the US, International and ETF markets. It also shows performance, valuations,etc... (always double check since free data sometimes is not reliable). Go to [finviz.com](https://finviz.com/map.ashx)

-   **MSCI World Index site**. This index tries to cover most of the investable equities in the world by free float. Go to the site [here](https://www.msci.com/indexes/index/990100) and check the factsheets (like [this one](https://www.msci.com/documents/10199/178e6643-6ae6-47b9-82be-e1fc565ededb)): it will show you weights by country and industry.

# 
